[project]
name = "test-species"
version = "0.1.0"
description = "SpeciesNet running as a LitServer"
readme = "README.md"
requires-python = ">=3.9,<3.15"
dependencies = [
    "speciesnet==5.0.0",
    "fastapi>=0.115.12",
    "litserve>=0.2.10",
]
